---
# playbook.yml
- name: 'IdM Image'
  hosts: default
  become: true

  pre_tasks:
    - name: enable repo
      shell: |
        dnf install -y epel-release
        yum -y  --nobest update 
      register: repo
    - debug: msg="{{ repo.stdout }}"
    - debug: msg="{{ repo.stderr }}"
    - name: update
      vars: 
        ansible_python_interpreter: /usr/bin/python2
      raw: yum install -y {{ item }}
      with_items:
        - python2
        - python3
        - git
        - xrdp

  tasks:
    - name: Enable idm
      shell: yum module enable -y idm:DL1

    - name: Enable xrdp
      service:
        name: xrdp
        state: started
        enabled: true
    - name: Add micro key
      shell: sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    - name: Create entry for create
      copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    - name: install code
      yum:
        name: code
    - name: add utils for packer and terraform
      yum:
        name: yum-utils
    - name: add repo
      shell: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - name: install terraform and packer
      yum:
        name: 
          - terraform
          - packer
          - ansible
          - ipa-server
          - ipa-server-dns

    - name: add to etc hosts file
      lineinfile:
        path: /etc/hosts
        line: '{{ ansible_default_ipv4.address }}    idm.alan-caldelas.com '
    - name: change hostname
      hostname:
        name: idm1.alan-caldelas.com

    - name: Open ports for idm
      firewalld: 
        port: '{{ item }}'
        permanent: yes  
        state: enabled
      with_items:
        - 80/tcp
        - 443/tcp
        - 389/tcp
        - 636/tcp
        - 88/tcp
        - 53/tcp
        - 464/udp
        - 8000/tcp
        - 3389/tcp
        - 53/udp
        - 3389/tcp
        - 123/udp
        