---
# playbook.yml
- name: 'K3s Server Image'
  hosts: localhost
  become: true

  pre_tasks:
    - name: enable repo
      shell: |
        dnf install -y epel-release
        yum -y update
    - name: update
      vars: 
        ansible_python_interpreter: /usr/bin/python2
      raw: yum install -y {{ item }}
      with_items:
        - python2
        - python3
        - git
        - xrdp

  tasks: 
    - name: Enable xrdp
      service:
        name: xrdp
        state: started
    - name: Add micro key
      shell: sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    - name: Create entry for create
      copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    - name: install code
      yum:
        name: code
    - name: add utils for packer and terraform
      yum:
        name: yum-utils
    - name: add repo
      shell: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - name: install terraform and packer
      yum:
        name: 
          - terraform
          - packer
          - ansible
          
    - name: Open ports for k3s
      firewalld: 
        port: '{{ item }}'
        permanent: yes  
        state: enabled
      with_items:
        - 6443/tcp
        - 8472/tcp
        - 10250/tcp
        - 2379-2380/tcp
        - 53/udp
        - 8080/tcp
        - 80/tcp
        - 8000/tcp
        - 3389/tcp

    - name: Download k3s
      get_url:
        url: '{{ item }}'
        dest: /var/tmp/
      with_items:
        - https://github.com/k3s-io/k3s-selinux/releases/download/v0.3.stable.0/k3s-selinux-0.3-0.el8.noarch.rpm
        - https://github.com/k3s-io/k3s/releases/download/v1.18.17%2Bk3s1/k3s-airgap-images-amd64.tar
        - https://github.com/k3s-io/k3s/releases/download/v1.18.17%2Bk3s1/k3s
    